### ISSUE TITLE
backticks causes error 

### ISSUE THREAD

**Issue by DDAZZA** [DDAZZA/renogen#8]
error when backticks are used in YAML file

Stacktrace:
```
~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse': (./change_log/next/test.yml): found character that cannot start any token while scanning for the next token at line 8 column 5 (Psych::SyntaxError)
        from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
        from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:325:in `parse'
        from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:252:in `load'
        from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:471:in `block in load_file'
        from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:471:in `open'
        from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:471:in `load_file'
```

**Comment by adamgeorgeson** [comment]
Would appear this is a limitation of YAML
http://yaml.org/spec/1.1/#id870830

Do we want to support this? Do we want to use YAML explicitly?

**Comment by DDAZZA** [comment]
We should probably return a better error message at least.

**Comment by wteuber** [comment]
I think https://github.com/DDAZZA/renogen/issues/1 covers that already, doesn't it?

**Comment by adamgeorgeson** [comment]
You're right @wteuber. Happy to close this as a dupe.
